import requests

url = "http://127.0.0.1:8000/predict"

# Base borrower profile (default values)
base_data = {
    "avg_cur_bal": 5000,
    "dti": 0.25,
    "acc_open_past_24mths": 2,
    "term": "60 months",
    "inq_last_12m": 1,
    "max_bal_bc": 10000,
    "desc": "Debt consolidation",
    "mths_since_recent_inq": 6,
    "open_rv_24m": 3,
    "loan_amnt": 15000,
    "num_actv_rev_tl": 4,
    "mort_acc": 1,
    "total_bal_il": 8000,
    "all_util": 0.45,
    "verification_status": "Source Verified",
    "home_ownership": "RENT",
    "int_rate": 12.5,
    "fico_range_low": 700,
    "sec_app_open_act_il": 0,
    "total_rev_hi_lim": 0,
    "mths_since_recent_il": 0,
    "il_util": 0,
    "sec_app_revol_util": 0,
    "total_bal_ex_mort": 0,
    "sec_app_earliest_cr_line": "2010-01",
    "open_acc": 0,
    "num_bc_tl": 0,
    "annual_inc": 50000,
    "addr_state": "CA",
    "sec_app_fico_range_low": 0,
    "pub_rec_bankruptcies": 0,
    "open_act_il": 0,
    "mths_since_last_major_derog": 0,
    "mths_since_last_record": 0,
    "num_tl_30dpd": 0,
    "revol_bal": 0,
    "total_cu_tl": 0,
    "initial_list_status": "W",
    "bc_util": 0,
    "sec_app_mort_acc": 0,
  "acc_now_delinq": 0,
  "sec_app_collections_12_mths_ex_med": 0,
  "title": "Other",
  "mths_since_recent_revol_delinq": 0,
  "purpose": "debt_consolidation",
  "mths_since_recent_bc": 0,
  "tax_liens": 0,
  "mths_since_recent_bc_dlq": 0,
  "revol_util": 0.45,
  "verification_status_joint": "Not Verified",
  "sec_app_open_acc": 0,
  "sec_app_num_rev_accts": 0,
  "collections_12_mths_ex_med": 0,
  "application_type": "Individual",
  "open_acc_6m": 0,
  "pct_tl_nvr_dlq": 100,
  "tot_coll_amt": 0,
  "num_il_tl": 0,
  "percent_bc_gt_75": 0,
  "annual_inc_joint": 0,
  "num_actv_bc_tl": 0,
  "num_op_rev_tl": 0,
  "num_tl_90g_dpd_24m": 0,
  "inq_fi": 0,
  "delinq_amnt": 0,
  "mths_since_last_delinq": 0,
  "chargeoff_within_12_mths": 0,
  "sec_app_inq_last_6mths": 0,
  "sec_app_mths_since_last_major_derog": 0,
  "mo_sin_old_il_acct": 0,
  "open_il_24m": 0,
  "bc_open_to_buy": 0,
  "tot_cur_bal": 0,
  "open_il_12m": 0,
  "earliest_cr_line": "2010-01",
  "disbursement_method": "Cash",
  "num_bc_sats": 0,
  "num_rev_accts": 0,
  "total_il_high_credit_limit": 0,
  "total_bc_limit": 0,
  "open_rv_12m": 0,
  "num_accts_ever_120_pd": 0,
  "revol_bal_joint": 0,
  "inq_last_6mths": 0,
  "pub_rec": 0,
  "emp_length": "10+ years",
  "num_tl_op_past_12m": 0,
  "delinq_2yrs": 0,
  "total_acc": 10,
  "mo_sin_rcnt_tl": 0,
  "mo_sin_rcnt_rev_tl_op": 0,
  "dti_joint": 0,
  "mths_since_rcnt_il": 0,
  "mo_sin_old_rev_tl_op": 0
}

# Define variations to test
test_cases = [
    {"loan_amnt": 5000, "dti": 0.1, "fico_range_low": 750},
    {"loan_amnt": 20000, "dti": 0.4, "fico_range_low": 650},
    {"loan_amnt": 10000, "dti": 0.2, "fico_range_low": 720},
    {"loan_amnt": 3000, "dti": 0.05, "fico_range_low": 780},
]

for i, case in enumerate(test_cases, 1):
    data = base_data.copy()
    data.update(case)  # update only the fields we want to test
    response = requests.post(url, json=data)
    if response.status_code == 200:
        print(f"Test case {i}: PD = {response.json()['pd']:.3f}")
    else:
        print(f"Test case {i}: Error {response.status_code} - {response.text}")
